AWSTemplateFormatVersion: 2010-09-09

Mappings:

  RegionMap:
    us-east-1:
      S3hostedzoneID: Z3AQBSTGFYJSTF
      websiteendpoint: s3-website-us-east-1.amazonaws.com

Parameters:

  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String
    Default: tier3.cloud

  SiteName:
    Description: Site name for your website
    Type: String
    Default: www

  GithubUsername:
    Type: String
    Default: tier3cloud
    Description: Oauth username for Github

  OAuthForGithub:
    Type: String
    Default: ""
    Description: Oauth token for Github

  GithubRepoName:
    Type: String
    Default: tier3.cloud
    Description: Name of github repo

  GithubBranchName:
    Type: String
    Default: master
    Description: Name of github branch

Resources:

  BuildObjectBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private

  WWWBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - .
        - - !Ref SiteName
          - !Ref RootDomainName
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  WWWBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WWWBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SiteName
                - .
                - !Ref RootDomainName
                - /*

  WebsiteDNSEntry:
    Type: 'AWS::Route53::RecordSetGroup'
    DependsOn: WWWBucket
    Properties:
      HostedZoneName: !Join 
        - ''
        - - !Ref RootDomainName
          - .
      Comment: Alias for site name to S3 bucket.
      RecordSets:
        - Name: !Join 
            - .
            - - !Ref SiteName
              - !Ref RootDomainName
          Type: CNAME
          TTL: '900'
          ResourceRecords:
            - !Join 
              - ''
              - - !Ref SiteName
                - .
                - !Ref RootDomainName
                - .
                - !FindInMap 
                  - RegionMap
                  - !Ref 'AWS::Region'
                  - websiteendpoint

  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /

  CodeBuildRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: CodeBuildRolePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource:
              - !Sub >-
                arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
          - Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${BuildObjectBucket}'
              - !Sub 'arn:aws:s3:::${BuildObjectBucket}/*'
              - !Sub 'arn:aws:s3:::${WWWBucket}'
              - !Sub 'arn:aws:s3:::${WWWBucket}/*'
            Action:
              - 's3:*'
      Roles:
        - !Ref CodeBuildRole

  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Name: !Sub '${AWS::StackName}-WWWBuilder'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/ubuntu-base:14.04'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUCKET_NAME
            Value: !Ref WWWBucket
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
      Tags:
        - Key: Stack
          Value: !Ref 'AWS::StackName'
      TimeoutInMinutes: 10
      
  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /

  CodePipelineRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: CodePipelineRolePolicy
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:GetBucketVersioning'
            Resource: '*'
            Effect: Allow
          - Action:
              - 's3:PutObject'
            Resource:
              - !Sub 'arn:aws:s3:::${BuildObjectBucket}'
              - !Sub 'arn:aws:s3:::${BuildObjectBucket}/*'
            Effect: Allow
          - Action:
              - 'codebuild:BatchGetBuilds'
              - 'codebuild:StartBuild'
            Resource: '*'
            Effect: Allow
      Roles:
        - !Ref CodePipelineRole

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt 
        - CodePipelineRole
        - Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: StaticSiteSource
              Configuration:
                Owner: !Ref GithubUsername
                Repo: !Ref GithubRepoName
                Branch: !Ref GithubBranchName
                OAuthToken: !Ref OAuthForGithub
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: StaticSiteSource
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: StaticSite
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref BuildObjectBucket